name: Playwright Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install deps
        run: npm ci

      - name: Install browsers
        run: npx playwright install --with-deps

      - name: Start local server
        run: |
          python3 -m http.server 8080 --directory site &
          echo $! > /tmp/http.pid

      - name: Run tests
        env:
          BASE_URL: http://127.0.0.1:8080
        run: npx playwright test

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report